version: '3.8'
networks:
  laravel: 
  vue:
services:
  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./src/backend:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - phpmyadmin
      
    networks:
      - laravel  

  php:
    build:
      context: ./dockerfiles
      dockerfile: laravel.dockerfile
    container_name: laravel-php  
    volumes:
      - ./src/backend:/var/www/html
    networks:
      - laravel  
    ports:
      - "8000:8000"   # Map port 8000 of the container to port 8000 of the host
    depends_on:
      - mysql

  vue:
    build:
      context: ./src/frontend
      dockerfile: dockerfile
    container_name: vue-site
    ports:
      - "3030:3030"
    depends_on:
      - php
      - nginx
    networks:
      - laravel  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    networks:
      - laravel  

  mysql:
    image: mysql:latest
    container_name: laravel-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: task_management
      MYSQL_USER: ajaxbo
      MYSQL_PASSWORD: ajaxbo360
      MYSQL_ROOT_PASSWORD: ajaxbo360
      # MYSQL_SERVICE_TAG: dev
      MYSQL_SERVICE_NAME: mysql
     
    networks:
      - laravel
